# Custom Language File for Launcher Customizer

[ejs.app]
title = "Damnatio Launcher"

[ejs.landing]
mediaGitHubURL = "https://damnatio.eu"
mediaTwitterURL = "#"
mediaInstagramURL = "https://www.instagram.com/damnatiomcj/"
mediaYouTubeURL = "https://www.youtube.com/@unevraifraise"
mediaDiscordURL = "https://discord.gg/ybKQPkZgCe"

[ejs.settings]
sourceGithubLink = "https://github.com/Siberkilleurs/DamnatioLauncher"
supportLink = "https://github.com/Siberkilleurs/DamnatioLauncher/issues"

[ejs.welcome]
welcomeHeader = "Welcome to Damnatio"
welcomeDescription = "Welcome on the official Damnatio Launcher"
welcomeDescCTA = "You are just a few clicks away."
